use std::collections::HashMap;

#[test]
fn test_vimrc_generator() {
    let mut values = HashMap::new();
    values.insert("syntax".to_string(), "true".to_string());
    values.insert("colorscheme".to_string(), "gruvbox".to_string());
    values.insert("background".to_string(), "dark".to_string());
    values.insert("number".to_string(), "true".to_string());
    values.insert("relativenumber".to_string(), "false".to_string());
    values.insert("tabstop".to_string(), "4".to_string());
    values.insert("shiftwidth".to_string(), "4".to_string());
    values.insert("expandtab".to_string(), "true".to_string());
    values.insert("hlsearch".to_string(), "true".to_string());
    values.insert("mouse".to_string(), "a".to_string());
    values.insert("laststatus".to_string(), "2".to_string());
    values.insert("scrolloff".to_string(), "5".to_string());

    let extra_lines = vec!["nnoremap <leader>f :Files<CR>".to_string()];

    // Inline generator logic for testing
    let mut lines = vec!["\" Generated by dot-config".to_string()];
    let get = |key: &str| values.get(key).map(|s| s.as_str()).unwrap_or("");

    if get("syntax") == "true" {
        lines.push("syntax on".into());
    }
    let cs = get("colorscheme");
    if !cs.is_empty() && cs != "default" {
        lines.push(format!("colorscheme {cs}"));
    }
    let bg = get("background");
    if !bg.is_empty() {
        lines.push(format!("set background={bg}"));
    }

    let toggles = ["number", "relativenumber", "expandtab", "hlsearch"];
    for key in toggles {
        let val = get(key);
        if val == "true" {
            lines.push(format!("set {key}"));
        } else if val == "false" {
            lines.push(format!("set no{key}"));
        }
    }

    let number_opts = ["tabstop", "shiftwidth", "scrolloff", "laststatus"];
    for key in number_opts {
        let val = get(key);
        if !val.is_empty() {
            lines.push(format!("set {key}={val}"));
        }
    }

    let mouse = get("mouse");
    if !mouse.is_empty() {
        lines.push(format!("set mouse={mouse}"));
    }

    if !extra_lines.is_empty() {
        lines.push(String::new());
        lines.push("\" User custom settings (preserved from import)".into());
        for line in &extra_lines {
            lines.push(line.clone());
        }
    }
    lines.push(String::new());

    let output = lines.join("\n");

    assert!(output.contains("\" Generated by dot-config"));
    assert!(output.contains("syntax on"));
    assert!(output.contains("colorscheme gruvbox"));
    assert!(output.contains("set background=dark"));
    assert!(output.contains("set number"));
    assert!(output.contains("set norelativenumber"));
    assert!(output.contains("set expandtab"));
    assert!(output.contains("set tabstop=4"));
    assert!(output.contains("set mouse=a"));
    assert!(output.contains("nnoremap <leader>f :Files<CR>"));
}

#[test]
fn test_gitconfig_generator() {
    let mut values = HashMap::new();
    values.insert("user.name".to_string(), "Jane Doe".to_string());
    values.insert("user.email".to_string(), "jane@example.com".to_string());
    values.insert("core.editor".to_string(), "nvim".to_string());
    values.insert("pull.rebase".to_string(), "true".to_string());
    values.insert("push.default".to_string(), "simple".to_string());
    values.insert("color.ui".to_string(), "auto".to_string());

    // Inline generator
    let mut lines = vec!["# Generated by dot-config".to_string()];
    let get = |key: &str| values.get(key).map(|s| s.as_str()).unwrap_or("");

    let sections: Vec<(&str, Vec<(&str, &str)>)> = vec![
        ("user", vec![("name", "user.name"), ("email", "user.email")]),
        ("core", vec![("editor", "core.editor")]),
        ("pull", vec![("rebase", "pull.rebase")]),
        ("push", vec![("default", "push.default")]),
        ("color", vec![("ui", "color.ui")]),
    ];

    for (section_name, keys) in sections {
        let mut section_lines = Vec::new();
        for (ini_key, schema_key) in keys {
            let val = get(schema_key);
            if !val.is_empty() {
                section_lines.push(format!("\t{ini_key} = {val}"));
            }
        }
        if !section_lines.is_empty() {
            lines.push(format!("[{section_name}]"));
            lines.extend(section_lines);
        }
    }
    lines.push(String::new());

    let output = lines.join("\n");

    assert!(output.contains("[user]"));
    assert!(output.contains("\tname = Jane Doe"));
    assert!(output.contains("\temail = jane@example.com"));
    assert!(output.contains("[core]"));
    assert!(output.contains("\teditor = nvim"));
    assert!(output.contains("[pull]"));
    assert!(output.contains("\trebase = true"));
    assert!(output.contains("[color]"));
    assert!(output.contains("\tui = auto"));
}

#[test]
fn test_tmux_generator() {
    let mut values = HashMap::new();
    values.insert("prefix".to_string(), "C-a".to_string());
    values.insert("mouse".to_string(), "true".to_string());
    values.insert("base-index".to_string(), "1".to_string());
    values.insert("history-limit".to_string(), "5000".to_string());
    values.insert("default-terminal".to_string(), "screen-256color".to_string());

    let mut lines = vec!["# Generated by dot-config".to_string()];
    let get = |key: &str| values.get(key).map(|s| s.as_str()).unwrap_or("");

    let prefix = get("prefix");
    if !prefix.is_empty() && prefix != "C-b" {
        lines.push("unbind C-b".into());
        lines.push(format!("set -g prefix {prefix}"));
        lines.push(format!("bind {prefix} send-prefix"));
    }

    if get("mouse") == "true" {
        lines.push("set -g mouse on".into());
    }
    let base = get("base-index");
    if !base.is_empty() {
        lines.push(format!("set -g base-index {base}"));
    }
    let hist = get("history-limit");
    if !hist.is_empty() {
        lines.push(format!("set -g history-limit {hist}"));
    }
    let term = get("default-terminal");
    if !term.is_empty() {
        lines.push(format!("set -g default-terminal \"{term}\""));
    }
    lines.push(String::new());

    let output = lines.join("\n");

    assert!(output.contains("unbind C-b"));
    assert!(output.contains("set -g prefix C-a"));
    assert!(output.contains("set -g mouse on"));
    assert!(output.contains("set -g base-index 1"));
    assert!(output.contains("set -g history-limit 5000"));
}
