use std::collections::HashMap;

pub fn generate_editorconfig(values: &HashMap<String, String>, extra_lines: &[String]) -> String {
    let mut lines = vec!["# Generated by dot-config".to_string()];

    let get = |key: &str| values.get(key).map(|s| s.as_str()).unwrap_or("");

    // Root setting
    let root = get("root");
    if root == "true" {
        lines.push("root = true".into());
    }

    lines.push(String::new());

    // Default section [*]
    lines.push("[*]".into());

    let indent_style = get("indent_style");
    if !indent_style.is_empty() {
        lines.push(format!("indent_style = {indent_style}"));
    }

    let indent_size = get("indent_size");
    if !indent_size.is_empty() {
        lines.push(format!("indent_size = {indent_size}"));
    }

    let eol = get("end_of_line");
    if !eol.is_empty() {
        lines.push(format!("end_of_line = {eol}"));
    }

    let charset = get("charset");
    if !charset.is_empty() {
        lines.push(format!("charset = {charset}"));
    }

    let trim = get("trim_trailing_whitespace");
    if !trim.is_empty() {
        lines.push(format!("trim_trailing_whitespace = {trim}"));
    }

    let final_newline = get("insert_final_newline");
    if !final_newline.is_empty() {
        lines.push(format!("insert_final_newline = {final_newline}"));
    }

    let max_line = get("max_line_length");
    if !max_line.is_empty() && max_line != "0" {
        lines.push(format!("max_line_length = {max_line}"));
    }

    // Makefile overrides
    let mk_indent = get("makefile_indent_style");
    if !mk_indent.is_empty() && mk_indent != indent_style {
        lines.push(String::new());
        lines.push("[Makefile]".into());
        lines.push(format!("indent_style = {mk_indent}"));
    }

    // Markdown overrides
    let md_trim = get("md_trim_trailing_whitespace");
    if !md_trim.is_empty() && md_trim != trim {
        lines.push(String::new());
        lines.push("[*.md]".into());
        lines.push(format!("trim_trailing_whitespace = {md_trim}"));
    }

    if !extra_lines.is_empty() {
        lines.push(String::new());
        lines.push("# User custom settings (preserved from import)".into());
        for line in extra_lines {
            lines.push(line.clone());
        }
    }

    lines.push(String::new());
    lines.join("\n")
}
