use std::collections::HashMap;

pub fn generate_emacs(values: &HashMap<String, String>, extra_lines: &[String]) -> String {
    let mut lines = vec![";; Generated by dot-config".to_string()];

    let get = |key: &str| values.get(key).map(|s| s.as_str()).unwrap_or("");

    // --- Appearance ---
    lines.push(String::new());
    lines.push(";; Appearance".into());

    // Mode toggles for appearance
    let appearance_modes = [
        "menu-bar-mode",
        "tool-bar-mode",
        "scroll-bar-mode",
        "show-paren-mode",
        "column-number-mode",
        "line-number-mode",
    ];
    for mode in appearance_modes {
        let val = get(mode);
        if val == "true" {
            lines.push(format!("({mode} 1)"));
        } else if val == "false" {
            lines.push(format!("({mode} -1)"));
        }
    }

    // setq appearance options
    let inhibit = get("inhibit-startup-screen");
    if inhibit == "true" {
        lines.push("(setq inhibit-startup-screen t)".into());
    } else if inhibit == "false" {
        lines.push("(setq inhibit-startup-screen nil)".into());
    }

    let visible_bell = get("visible-bell");
    if visible_bell == "true" {
        lines.push("(setq visible-bell t)".into());
    } else if visible_bell == "false" {
        lines.push("(setq visible-bell nil)".into());
    }

    let display_ln = get("display-line-numbers");
    if !display_ln.is_empty() && display_ln != "nil" {
        if display_ln == "t" {
            lines.push("(setq display-line-numbers t)".into());
        } else {
            lines.push(format!("(setq display-line-numbers '{display_ln})"));
        }
        lines.push("(global-display-line-numbers-mode 1)".into());
    }

    // --- Editing ---
    lines.push(String::new());
    lines.push(";; Editing".into());

    let indent_tabs = get("indent-tabs-mode");
    if indent_tabs == "true" {
        lines.push("(setq-default indent-tabs-mode t)".into());
    } else if indent_tabs == "false" {
        lines.push("(setq-default indent-tabs-mode nil)".into());
    }

    let tab_width = get("tab-width");
    if !tab_width.is_empty() {
        lines.push(format!("(setq-default tab-width {tab_width})"));
    }

    let fill_column = get("fill-column");
    if !fill_column.is_empty() {
        lines.push(format!("(setq-default fill-column {fill_column})"));
    }

    let require_nl = get("require-final-newline");
    if require_nl == "true" {
        lines.push("(setq require-final-newline t)".into());
    } else if require_nl == "false" {
        lines.push("(setq require-final-newline nil)".into());
    }

    let editing_modes = [
        "delete-selection-mode",
        "electric-pair-mode",
    ];
    for mode in editing_modes {
        let val = get(mode);
        if val == "true" {
            lines.push(format!("({mode} 1)"));
        } else if val == "false" {
            lines.push(format!("({mode} -1)"));
        }
    }

    // --- Backup & Files ---
    lines.push(String::new());
    lines.push(";; Backup & Files".into());

    let backup_toggle_opts = [
        ("make-backup-files", "make-backup-files"),
        ("auto-save-default", "auto-save-default"),
        ("create-lockfiles", "create-lockfiles"),
    ];
    for (setq_key, schema_key) in backup_toggle_opts {
        let val = get(schema_key);
        if val == "true" {
            lines.push(format!("(setq {setq_key} t)"));
        } else if val == "false" {
            lines.push(format!("(setq {setq_key} nil)"));
        }
    }

    let auto_revert = get("auto-revert-mode");
    if auto_revert == "true" {
        lines.push("(global-auto-revert-mode 1)".into());
    } else if auto_revert == "false" {
        lines.push("(global-auto-revert-mode -1)".into());
    }

    // --- Behavior ---
    lines.push(String::new());
    lines.push(";; Behavior".into());

    let ring_bell = get("ring-bell-function");
    if ring_bell == "ignore" {
        lines.push("(setq ring-bell-function 'ignore)".into());
    } else if ring_bell == "ding" {
        lines.push("(setq ring-bell-function 'ding)".into());
    }

    let scroll = get("scroll-conservatively");
    if !scroll.is_empty() {
        lines.push(format!("(setq scroll-conservatively {scroll})"));
    }

    let short_answers = get("use-short-answers");
    if short_answers == "true" {
        lines.push("(setq use-short-answers t)".into());
    } else if short_answers == "false" {
        lines.push("(setq use-short-answers nil)".into());
    }

    let behavior_modes = [
        "ido-mode",
        "save-place-mode",
    ];
    for mode in behavior_modes {
        let val = get(mode);
        if val == "true" {
            lines.push(format!("({mode} 1)"));
        } else if val == "false" {
            lines.push(format!("({mode} -1)"));
        }
    }

    if !extra_lines.is_empty() {
        lines.push(String::new());
        lines.push(";; User custom settings (preserved from import)".into());
        for line in extra_lines {
            lines.push(line.clone());
        }
    }

    lines.push(String::new());
    lines.join("\n")
}
