use std::collections::HashMap;

pub fn generate_gitconfig(values: &HashMap<String, String>, extra_lines: &[String]) -> String {
    let mut lines = vec!["# Generated by dot-config".to_string()];

    let get = |key: &str| values.get(key).map(|s| s.as_str()).unwrap_or("");

    // Group options by section (based on dotted key)
    let sections: Vec<(&str, Vec<(&str, &str)>)> = vec![
        ("user", vec![
            ("name", "user.name"),
            ("email", "user.email"),
        ]),
        ("core", vec![
            ("editor", "core.editor"),
            ("autocrlf", "core.autocrlf"),
            ("whitespace", "core.whitespace"),
        ]),
        ("init", vec![
            ("defaultBranch", "init.defaultBranch"),
        ]),
        ("pull", vec![
            ("rebase", "pull.rebase"),
        ]),
        ("push", vec![
            ("default", "push.default"),
        ]),
        ("merge", vec![
            ("conflictstyle", "merge.conflictstyle"),
        ]),
        ("color", vec![
            ("ui", "color.ui"),
        ]),
        ("help", vec![
            ("autocorrect", "help.autocorrect"),
        ]),
        ("rerere", vec![
            ("enabled", "rerere.enabled"),
        ]),
    ];

    for (section_name, keys) in sections {
        let mut section_lines = Vec::new();
        for (ini_key, schema_key) in keys {
            let val = get(schema_key);
            if !val.is_empty() {
                section_lines.push(format!("\t{ini_key} = {val}"));
            }
        }
        if !section_lines.is_empty() {
            lines.push(format!("[{section_name}]"));
            lines.extend(section_lines);
        }
    }

    if !extra_lines.is_empty() {
        lines.push(String::new());
        lines.push("# User custom settings (preserved from import)".into());
        for line in extra_lines {
            lines.push(line.clone());
        }
    }

    lines.push(String::new());
    lines.join("\n")
}
