use std::collections::HashMap;

pub fn generate_inputrc(values: &HashMap<String, String>, extra_lines: &[String]) -> String {
    let mut lines = vec!["# Generated by dot-config".to_string()];

    let get = |key: &str| values.get(key).map(|s| s.as_str()).unwrap_or("");

    // String options
    let string_opts = [
        "editing-mode",
        "keymap",
        "bell-style",
    ];
    for key in string_opts {
        let val = get(key);
        if !val.is_empty() {
            lines.push(format!("set {key} {val}"));
        }
    }

    // Toggle options
    let toggle_opts = [
        "completion-ignore-case",
        "completion-map-case",
        "show-all-if-ambiguous",
        "show-all-if-unmodified",
        "menu-complete-display-prefix",
        "colored-completion-prefix",
        "colored-stats",
        "visible-stats",
        "revert-all-at-newline",
        "mark-symlinked-directories",
        "skip-completed-text",
    ];
    for key in toggle_opts {
        let val = get(key);
        if val == "true" {
            lines.push(format!("set {key} on"));
        } else if val == "false" {
            lines.push(format!("set {key} off"));
        }
    }

    // Number options
    let history_size = get("history-size");
    if !history_size.is_empty() {
        lines.push(format!("set history-size {history_size}"));
    }

    if !extra_lines.is_empty() {
        lines.push(String::new());
        lines.push("# User custom settings (preserved from import)".into());
        for line in extra_lines {
            lines.push(line.clone());
        }
    }

    lines.push(String::new());
    lines.join("\n")
}
