use std::collections::HashMap;

pub fn generate_shellrc(values: &HashMap<String, String>, extra_lines: &[String]) -> String {
    let mut lines = vec!["# Generated by dot-config".to_string()];

    let get = |key: &str| values.get(key).map(|s| s.as_str()).unwrap_or("");

    // Environment variables
    for key in ["EDITOR", "VISUAL", "LANG"] {
        let val = get(key);
        if !val.is_empty() {
            lines.push(format!("export {key}=\"{val}\""));
        }
    }

    // History settings
    for key in ["HISTSIZE", "HISTFILESIZE", "HISTCONTROL"] {
        let val = get(key);
        if !val.is_empty() {
            lines.push(format!("export {key}={val}"));
        }
    }

    // Shell options (shopt)
    if get("hist_append") == "true" {
        lines.push("shopt -s histappend".into());
    }
    let shopts = ["checkwinsize", "globstar", "cdspell", "autocd"];
    for key in shopts {
        if get(key) == "true" {
            lines.push(format!("shopt -s {key}"));
        }
    }

    // Aliases
    lines.push(String::new());
    if get("alias_ll") == "true" {
        lines.push("alias ll='ls -alF'".into());
    }
    if get("alias_la") == "true" {
        lines.push("alias la='ls -A'".into());
    }
    if get("alias_grep_color") == "true" {
        lines.push("alias grep='grep --color=auto'".into());
        lines.push("alias fgrep='fgrep --color=auto'".into());
        lines.push("alias egrep='egrep --color=auto'".into());
    }
    if get("alias_rm_confirm") == "true" {
        lines.push("alias rm='rm -i'".into());
    }
    if get("alias_cp_confirm") == "true" {
        lines.push("alias cp='cp -i'".into());
    }

    if !extra_lines.is_empty() {
        lines.push(String::new());
        lines.push("# User custom settings (preserved from import)".into());
        for line in extra_lines {
            lines.push(line.clone());
        }
    }

    lines.push(String::new());
    lines.join("\n")
}
