use std::collections::HashMap;

/// Each entry in the list is one Host block's values.
pub fn generate_ssh(hosts: &[HashMap<String, String>], extra_lines: &[String]) -> String {
    let mut lines = vec!["# Generated by dot-config".to_string()];

    for host_values in hosts {
        let get = |key: &str| host_values.get(key).map(|s| s.as_str()).unwrap_or("");

        let host_alias = get("Host");
        if host_alias.is_empty() {
            continue;
        }

        lines.push(String::new());
        lines.push(format!("Host {host_alias}"));

        let keys = [
            "HostName", "User", "Port", "IdentityFile",
            "AddKeysToAgent", "ForwardAgent", "StrictHostKeyChecking",
            "ServerAliveInterval", "ServerAliveCountMax",
        ];

        for key in keys {
            let val = get(key);
            if !val.is_empty() {
                // Convert toggle values
                let val = match val {
                    "true" => "yes",
                    "false" => "no",
                    other => other,
                };
                // Skip default port
                if key == "Port" && val == "22" {
                    continue;
                }
                lines.push(format!("    {key} {val}"));
            }
        }
    }

    if !extra_lines.is_empty() {
        lines.push(String::new());
        lines.push("# User custom settings (preserved from import)".into());
        for line in extra_lines {
            lines.push(line.clone());
        }
    }

    lines.push(String::new());
    lines.join("\n")
}
