use std::collections::HashMap;

pub fn generate_tmux(values: &HashMap<String, String>, extra_lines: &[String]) -> String {
    let mut lines = vec!["# Generated by dot-config".to_string()];

    let get = |key: &str| values.get(key).map(|s| s.as_str()).unwrap_or("");

    // Prefix key
    let prefix = get("prefix");
    if !prefix.is_empty() && prefix != "C-b" {
        lines.push("unbind C-b".into());
        lines.push(format!("set -g prefix {prefix}"));
        lines.push(format!("bind {prefix} send-prefix"));
    }

    // Toggle options
    let toggle_opts = [
        ("mouse", "mouse"),
        ("renumber-windows", "renumber-windows"),
        ("monitor-activity", "monitor-activity"),
        ("visual-activity", "visual-activity"),
    ];
    for (tmux_key, schema_key) in toggle_opts {
        let val = get(schema_key);
        if val == "true" {
            lines.push(format!("set -g {tmux_key} on"));
        } else if val == "false" {
            lines.push(format!("set -g {tmux_key} off"));
        }
    }

    // Number options
    let number_opts = [
        ("base-index", "base-index"),
        ("pane-base-index", "pane-base-index"),
        ("history-limit", "history-limit"),
        ("escape-time", "escape-time"),
        ("display-time", "display-time"),
    ];
    for (tmux_key, schema_key) in number_opts {
        let val = get(schema_key);
        if !val.is_empty() {
            // pane-base-index uses setw
            if tmux_key == "pane-base-index" {
                lines.push(format!("setw -g {tmux_key} {val}"));
            } else {
                lines.push(format!("set -g {tmux_key} {val}"));
            }
        }
    }

    // String options
    let default_term = get("default-terminal");
    if !default_term.is_empty() {
        lines.push(format!("set -g default-terminal \"{default_term}\""));
    }

    let status_pos = get("status-position");
    if !status_pos.is_empty() {
        lines.push(format!("set -g status-position {status_pos}"));
    }

    if !extra_lines.is_empty() {
        lines.push(String::new());
        lines.push("# User custom settings (preserved from import)".into());
        for line in extra_lines {
            lines.push(line.clone());
        }
    }

    lines.push(String::new());
    lines.join("\n")
}
