use std::collections::HashMap;

pub fn generate_vimrc(values: &HashMap<String, String>, extra_lines: &[String]) -> String {
    let mut lines = vec!["\" Generated by dot-config".to_string()];

    let get = |key: &str| values.get(key).map(|s| s.as_str()).unwrap_or("");

    // Encoding
    let enc = get("encoding");
    if !enc.is_empty() && enc != "utf-8" {
        lines.push(format!("set encoding={enc}"));
    } else if enc == "utf-8" {
        lines.push("set encoding=utf-8".into());
    }

    // Syntax
    if get("syntax") == "true" {
        lines.push("syntax on".into());
    }

    // Filetype indent
    if get("filetype_indent") == "true" {
        lines.push("filetype plugin indent on".into());
    }

    // Color scheme
    let cs = get("colorscheme");
    if !cs.is_empty() && cs != "default" {
        lines.push(format!("colorscheme {cs}"));
    }

    // Background
    let bg = get("background");
    if !bg.is_empty() {
        lines.push(format!("set background={bg}"));
    }

    // True color
    if get("termguicolors") == "true" {
        lines.push("set termguicolors".into());
    }

    // Toggle options
    let toggles = [
        "number", "relativenumber", "cursorline", "cursorcolumn",
        "showcmd", "showmode", "ruler",
        "expandtab", "autoindent", "smartindent",
        "hlsearch", "incsearch", "ignorecase", "smartcase",
        "hidden", "wildmenu", "wrap",
        "splitbelow", "splitright",
        "undofile", "backup", "swapfile", "autoread",
    ];
    for key in toggles {
        let val = get(key);
        if val == "true" {
            lines.push(format!("set {key}"));
        } else if val == "false" {
            lines.push(format!("set no{key}"));
        }
    }

    // Number options
    let number_opts = [
        "tabstop", "softtabstop", "shiftwidth",
        "scrolloff", "laststatus", "updatetime",
    ];
    for key in number_opts {
        let val = get(key);
        if !val.is_empty() {
            lines.push(format!("set {key}={val}"));
        }
    }

    // Mouse
    let mouse = get("mouse");
    if !mouse.is_empty() {
        lines.push(format!("set mouse={mouse}"));
    }

    // Clipboard
    let clip = get("clipboard");
    if !clip.is_empty() {
        lines.push(format!("set clipboard={clip}"));
    }

    // Backspace
    let bs = get("backspace");
    if !bs.is_empty() {
        lines.push(format!("set backspace={bs}"));
    }

    // Sign column
    let sc = get("signcolumn");
    if !sc.is_empty() {
        lines.push(format!("set signcolumn={sc}"));
    }

    // Extra lines (unrecognized from import)
    if !extra_lines.is_empty() {
        lines.push(String::new());
        lines.push("\" User custom settings (preserved from import)".into());
        for line in extra_lines {
            lines.push(line.clone());
        }
    }

    lines.push(String::new()); // trailing newline
    lines.join("\n")
}
