use std::collections::HashMap;

pub fn generate_wgetrc(values: &HashMap<String, String>, extra_lines: &[String]) -> String {
    let mut lines = vec!["# Generated by dot-config".to_string()];

    let get = |key: &str| values.get(key).map(|s| s.as_str()).unwrap_or("");

    // Number options
    let number_opts = [
        "tries",
        "timeout",
        "waitretry",
    ];
    for key in number_opts {
        let val = get(key);
        if !val.is_empty() {
            lines.push(format!("{key} = {val}"));
        }
    }

    // Toggle options
    let toggle_opts = [
        "continue",
        "timestamping",
        "no_parent",
        "adjust_extension",
        "check_certificate",
        "https_only",
        "verbose",
        "server_response",
    ];
    for key in toggle_opts {
        let val = get(key);
        if val == "true" {
            lines.push(format!("{key} = on"));
        } else if val == "false" {
            lines.push(format!("{key} = off"));
        }
    }

    // String options
    let dot_style = get("dot_style");
    if !dot_style.is_empty() {
        lines.push(format!("dot_style = {dot_style}"));
    }

    if !extra_lines.is_empty() {
        lines.push(String::new());
        lines.push("# User custom settings (preserved from import)".into());
        for line in extra_lines {
            lines.push(line.clone());
        }
    }

    lines.push(String::new());
    lines.join("\n")
}
