use std::collections::HashMap;

use crate::models::config_state::DotfileState;

pub fn parse_inputrc(content: &str) -> DotfileState {
    let mut values = HashMap::new();
    let mut extra_lines = Vec::new();

    let toggle_opts = [
        "completion-ignore-case",
        "completion-map-case",
        "show-all-if-ambiguous",
        "show-all-if-unmodified",
        "menu-complete-display-prefix",
        "colored-completion-prefix",
        "colored-stats",
        "visible-stats",
        "revert-all-at-newline",
        "mark-symlinked-directories",
        "skip-completed-text",
    ];

    let string_opts = [
        "editing-mode",
        "keymap",
        "bell-style",
    ];

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.is_empty() || trimmed.starts_with("# Generated by dot-config") {
            continue;
        }

        // Parse "set variable value"
        if let Some(rest) = trimmed.strip_prefix("set ") {
            if let Some((key, val)) = rest.split_once(char::is_whitespace) {
                let key = key.trim();
                let val = val.trim();

                if toggle_opts.contains(&key) {
                    let bool_val = match val {
                        "on" | "On" | "ON" => "true",
                        "off" | "Off" | "OFF" => "false",
                        _ => val,
                    };
                    values.insert(key.into(), bool_val.into());
                    continue;
                }

                if string_opts.contains(&key) {
                    values.insert(key.into(), val.into());
                    continue;
                }

                if key == "history-size" {
                    values.insert(key.into(), val.into());
                    continue;
                }
            }
        }

        if !trimmed.starts_with("# User custom settings") {
            extra_lines.push(line.to_string());
        }
    }

    DotfileState {
        values,
        extra_lines,
        file_exists: true,
    }
}
