use std::collections::HashMap;

use crate::models::config_state::DotfileState;

pub fn parse_npmrc(content: &str) -> DotfileState {
    let mut values = HashMap::new();
    let mut extra_lines = Vec::new();

    let toggle_opts = [
        "save-exact",
        "package-lock",
        "fund",
        "audit",
        "progress",
        "engine-strict",
    ];

    let text_opts = [
        "registry",
        "init-author-name",
        "init-author-email",
    ];

    let string_opts = [
        "save-prefix",
        "loglevel",
        "init-license",
    ];

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.is_empty()
            || trimmed.starts_with(';')
            || trimmed.starts_with("# Generated by dot-config")
        {
            continue;
        }

        if trimmed.starts_with('#') {
            if !trimmed.starts_with("# User custom settings") {
                extra_lines.push(line.to_string());
            }
            continue;
        }

        // Parse key=value
        if let Some((key, val)) = trimmed.split_once('=') {
            let key = key.trim();
            let val = val.trim();

            if toggle_opts.contains(&key) {
                values.insert(key.into(), val.into());
                continue;
            }

            if text_opts.contains(&key) {
                values.insert(key.into(), val.into());
                continue;
            }

            if string_opts.contains(&key) {
                values.insert(key.into(), val.into());
                continue;
            }

            // Unknown key - preserve
            extra_lines.push(line.to_string());
            continue;
        }

        extra_lines.push(line.to_string());
    }

    DotfileState {
        values,
        extra_lines,
        file_exists: true,
    }
}
