use std::collections::HashMap;

use crate::models::config_state::DotfileState;

pub fn parse_shellrc(content: &str) -> DotfileState {
    let mut values = HashMap::new();
    let mut extra_lines = Vec::new();

    let env_vars = ["EDITOR", "VISUAL", "LANG", "HISTSIZE", "HISTFILESIZE", "HISTCONTROL"];
    let shopts = ["checkwinsize", "globstar", "cdspell", "autocd"];

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.is_empty() || trimmed.starts_with("# Generated by dot-config") {
            continue;
        }

        // Parse export VAR=value or export VAR="value"
        if let Some(rest) = trimmed.strip_prefix("export ") {
            if let Some((key, val)) = rest.split_once('=') {
                let key = key.trim();
                let val = val.trim().trim_matches('"').trim_matches('\'');
                if env_vars.contains(&key) {
                    values.insert(key.into(), val.into());
                    continue;
                }
            }
        }

        // Parse shopt -s option
        if let Some(rest) = trimmed.strip_prefix("shopt -s ") {
            let opt = rest.trim();
            if opt == "histappend" {
                values.insert("hist_append".into(), "true".into());
                continue;
            }
            if shopts.contains(&opt) {
                values.insert(opt.into(), "true".into());
                continue;
            }
        }

        // Parse aliases
        if trimmed.starts_with("alias ll=") {
            values.insert("alias_ll".into(), "true".into());
            continue;
        }
        if trimmed.starts_with("alias la=") {
            values.insert("alias_la".into(), "true".into());
            continue;
        }
        if trimmed == "alias grep='grep --color=auto'" || trimmed == "alias grep=\"grep --color=auto\"" {
            values.insert("alias_grep_color".into(), "true".into());
            continue;
        }
        if trimmed.starts_with("alias rm='rm -i'") || trimmed.starts_with("alias rm=\"rm -i\"") {
            values.insert("alias_rm_confirm".into(), "true".into());
            continue;
        }
        if trimmed.starts_with("alias cp='cp -i'") || trimmed.starts_with("alias cp=\"cp -i\"") {
            values.insert("alias_cp_confirm".into(), "true".into());
            continue;
        }

        // Skip known generated aliases that are side effects
        if trimmed.starts_with("alias fgrep=") || trimmed.starts_with("alias egrep=") {
            continue;
        }

        if !trimmed.starts_with("# User custom settings") {
            extra_lines.push(line.to_string());
        }
    }

    DotfileState {
        values,
        extra_lines,
        file_exists: true,
    }
}
