use std::collections::HashMap;

/// Parse SSH config into a list of host blocks.
/// Returns (hosts, extra_lines).
pub fn parse_ssh(content: &str) -> (Vec<HashMap<String, String>>, Vec<String>) {
    let mut hosts: Vec<HashMap<String, String>> = Vec::new();
    let mut extra_lines = Vec::new();
    let mut current_host: Option<HashMap<String, String>> = None;

    let known_keys = [
        "HostName", "User", "Port", "IdentityFile",
        "AddKeysToAgent", "ForwardAgent", "StrictHostKeyChecking",
        "ServerAliveInterval", "ServerAliveCountMax",
    ];

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.is_empty() || trimmed.starts_with("# Generated by dot-config") {
            continue;
        }

        // Host line
        if let Some(host) = trimmed.strip_prefix("Host ") {
            if let Some(prev) = current_host.take() {
                hosts.push(prev);
            }
            let mut h = HashMap::new();
            h.insert("Host".into(), host.trim().into());
            current_host = Some(h);
            continue;
        }

        if let Some(ref mut host) = current_host {
            // Parse "Key value" inside a host block
            if let Some((key, val)) = trimmed.split_once(char::is_whitespace) {
                let key = key.trim();
                let val = val.trim();

                if known_keys.iter().any(|k| k.eq_ignore_ascii_case(key)) {
                    // Normalize key casing
                    let canonical_key = known_keys.iter()
                        .find(|k| k.eq_ignore_ascii_case(key))
                        .unwrap_or(&key);
                    // Convert yes/no to true/false for ForwardAgent toggle
                    let val = if *canonical_key == "ForwardAgent" {
                        match val {
                            "yes" => "true",
                            "no" => "false",
                            _ => val,
                        }
                    } else {
                        val
                    };
                    host.insert(canonical_key.to_string(), val.into());
                    continue;
                }
            }
        }

        if !trimmed.starts_with('#') || !trimmed.contains("User custom settings") {
            extra_lines.push(line.to_string());
        }
    }

    if let Some(prev) = current_host {
        hosts.push(prev);
    }

    (hosts, extra_lines)
}
