use std::collections::HashMap;

use crate::models::config_state::DotfileState;

pub fn parse_tmux(content: &str) -> DotfileState {
    let mut values = HashMap::new();
    let mut extra_lines = Vec::new();

    let toggle_opts = [
        "mouse", "renumber-windows", "monitor-activity", "visual-activity",
    ];
    let number_opts = [
        "base-index", "pane-base-index", "history-limit", "escape-time", "display-time",
    ];

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.is_empty() || trimmed.starts_with("# Generated by dot-config") {
            continue;
        }

        // Parse "set -g key value" or "setw -g key value"
        let rest = if let Some(r) = trimmed.strip_prefix("set -g ") {
            Some(r)
        } else if let Some(r) = trimmed.strip_prefix("set-option -g ") {
            Some(r)
        } else if let Some(r) = trimmed.strip_prefix("setw -g ") {
            Some(r)
        } else if let Some(r) = trimmed.strip_prefix("set-window-option -g ") {
            Some(r)
        } else {
            None
        };

        if let Some(rest) = rest {
            if let Some((key, val)) = rest.split_once(char::is_whitespace) {
                let key = key.trim();
                let val = val.trim().trim_matches('"');

                if toggle_opts.contains(&key) {
                    let bool_val = match val {
                        "on" => "true",
                        "off" => "false",
                        _ => val,
                    };
                    values.insert(key.into(), bool_val.into());
                    continue;
                }

                if number_opts.contains(&key) {
                    values.insert(key.into(), val.into());
                    continue;
                }

                if key == "prefix" {
                    values.insert("prefix".into(), val.into());
                    continue;
                }

                if key == "default-terminal" {
                    values.insert("default-terminal".into(), val.into());
                    continue;
                }

                if key == "status-position" {
                    values.insert("status-position".into(), val.into());
                    continue;
                }
            }
        }

        // Skip known generated prefix lines
        if trimmed.starts_with("unbind ") || trimmed.starts_with("bind ") {
            // These are likely generated prefix lines - still preserve them
            // unless they match our pattern
            if trimmed == "unbind C-b" {
                continue;
            }
            if trimmed.contains("send-prefix") {
                continue;
            }
        }

        if !trimmed.starts_with("# User custom settings") {
            extra_lines.push(line.to_string());
        }
    }

    DotfileState {
        values,
        extra_lines,
        file_exists: true,
    }
}
