use std::collections::HashMap;

use crate::models::config_state::DotfileState;

pub fn parse_wgetrc(content: &str) -> DotfileState {
    let mut values = HashMap::new();
    let mut extra_lines = Vec::new();

    let toggle_opts = [
        "continue",
        "timestamping",
        "no_parent",
        "adjust_extension",
        "check_certificate",
        "https_only",
        "verbose",
        "server_response",
    ];

    let number_opts = [
        "tries",
        "timeout",
        "waitretry",
    ];

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.is_empty() || trimmed.starts_with("# Generated by dot-config") {
            continue;
        }

        if trimmed.starts_with('#') {
            if !trimmed.starts_with("# User custom settings") {
                extra_lines.push(line.to_string());
            }
            continue;
        }

        // Parse key = value (wget uses spaces around =)
        if let Some((key, val)) = trimmed.split_once('=') {
            let key = key.trim();
            let val = val.trim();

            if toggle_opts.contains(&key) {
                let bool_val = match val {
                    "on" | "On" | "ON" => "true",
                    "off" | "Off" | "OFF" => "false",
                    _ => val,
                };
                values.insert(key.into(), bool_val.into());
                continue;
            }

            if number_opts.contains(&key) {
                values.insert(key.into(), val.into());
                continue;
            }

            if key == "dot_style" {
                values.insert(key.into(), val.into());
                continue;
            }

            // Unknown key - preserve
            extra_lines.push(line.to_string());
            continue;
        }

        extra_lines.push(line.to_string());
    }

    DotfileState {
        values,
        extra_lines,
        file_exists: true,
    }
}
