use super::schema::{ConfigSchema, DotfileType, OptionDef, OptionKind};

pub fn emacs_schema() -> ConfigSchema {
    ConfigSchema {
        name: "Emacs".into(),
        dotfile_type: DotfileType::Emacs,
        default_path: "~/.emacs".into(),
        options: vec![
            // Appearance
            OptionDef {
                key: "inhibit-startup-screen".into(),
                label: "Inhibit Startup Screen".into(),
                help: "Skip the splash screen on startup".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "visible-bell".into(),
                label: "Visible Bell".into(),
                help: "Flash the screen instead of audible bell".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "column-number-mode".into(),
                label: "Column Number Mode".into(),
                help: "Show column number in the mode line".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "line-number-mode".into(),
                label: "Line Number Mode".into(),
                help: "Show line number in the mode line".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "display-line-numbers".into(),
                label: "Display Line Numbers".into(),
                help: "Show line numbers in the left margin".into(),
                section: "Appearance".into(),
                kind: OptionKind::Dropdown(vec![
                    ("nil".into(), "Off".into()),
                    ("t".into(), "Absolute".into()),
                    ("relative".into(), "Relative".into()),
                    ("visual".into(), "Visual".into()),
                ]),
                default: "t".into(),
            },
            OptionDef {
                key: "show-paren-mode".into(),
                label: "Show Paren Mode".into(),
                help: "Highlight matching parentheses".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "menu-bar-mode".into(),
                label: "Menu Bar".into(),
                help: "Show the menu bar at the top".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
            OptionDef {
                key: "tool-bar-mode".into(),
                label: "Tool Bar".into(),
                help: "Show the tool bar with icons".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
            OptionDef {
                key: "scroll-bar-mode".into(),
                label: "Scroll Bar".into(),
                help: "Show scroll bars".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
            // Editing
            OptionDef {
                key: "indent-tabs-mode".into(),
                label: "Indent With Tabs".into(),
                help: "Use tabs for indentation instead of spaces".into(),
                section: "Editing".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
            OptionDef {
                key: "tab-width".into(),
                label: "Tab Width".into(),
                help: "Display width of a tab character".into(),
                section: "Editing".into(),
                kind: OptionKind::Number { min: 2, max: 8, step: 1 },
                default: "4".into(),
            },
            OptionDef {
                key: "fill-column".into(),
                label: "Fill Column".into(),
                help: "Column beyond which automatic line-wrapping starts".into(),
                section: "Editing".into(),
                kind: OptionKind::Number { min: 40, max: 200, step: 10 },
                default: "80".into(),
            },
            OptionDef {
                key: "require-final-newline".into(),
                label: "Require Final Newline".into(),
                help: "Ensure files end with a newline on save".into(),
                section: "Editing".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "delete-selection-mode".into(),
                label: "Delete Selection Mode".into(),
                help: "Typing replaces the active selection".into(),
                section: "Editing".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "electric-pair-mode".into(),
                label: "Electric Pair Mode".into(),
                help: "Auto-insert matching brackets and quotes".into(),
                section: "Editing".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            // Backup & Files
            OptionDef {
                key: "make-backup-files".into(),
                label: "Backup Files".into(),
                help: "Create backup files (file~) on save".into(),
                section: "Backup & Files".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
            OptionDef {
                key: "auto-save-default".into(),
                label: "Auto Save".into(),
                help: "Periodically auto-save file contents".into(),
                section: "Backup & Files".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "create-lockfiles".into(),
                label: "Lock Files".into(),
                help: "Create .#file lock files when editing".into(),
                section: "Backup & Files".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
            OptionDef {
                key: "auto-revert-mode".into(),
                label: "Auto Revert".into(),
                help: "Automatically reload files changed on disk".into(),
                section: "Backup & Files".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            // Behavior
            OptionDef {
                key: "ring-bell-function".into(),
                label: "Ring Bell Function".into(),
                help: "What happens when Emacs wants to ring the bell".into(),
                section: "Behavior".into(),
                kind: OptionKind::Dropdown(vec![
                    ("ignore".into(), "Ignore (silent)".into()),
                    ("ding".into(), "Ding (default beep)".into()),
                ]),
                default: "ignore".into(),
            },
            OptionDef {
                key: "scroll-conservatively".into(),
                label: "Scroll Conservatively".into(),
                help: "Lines to scroll to bring point into view (high = smooth)".into(),
                section: "Behavior".into(),
                kind: OptionKind::Number { min: 0, max: 10000, step: 100 },
                default: "10000".into(),
            },
            OptionDef {
                key: "use-short-answers".into(),
                label: "Short Answers".into(),
                help: "Accept 'y' or 'n' instead of 'yes' or 'no'".into(),
                section: "Behavior".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "ido-mode".into(),
                label: "Ido Mode".into(),
                help: "Interactively Do Things for buffer/file completion".into(),
                section: "Behavior".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "save-place-mode".into(),
                label: "Save Place Mode".into(),
                help: "Remember cursor position in previously visited files".into(),
                section: "Behavior".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
        ],
    }
}
