use super::schema::{ConfigSchema, DotfileType, OptionDef, OptionKind};

pub fn shellrc_schema() -> ConfigSchema {
    ConfigSchema {
        name: "Shell (Bash/Zsh)".into(),
        dotfile_type: DotfileType::Shellrc,
        default_path: "~/.bashrc".into(),
        options: vec![
            // Environment
            OptionDef {
                key: "EDITOR".into(),
                label: "Default Editor".into(),
                help: "Set the default text editor".into(),
                section: "Environment".into(),
                kind: OptionKind::Dropdown(vec![
                    ("vim".into(), "Vim".into()),
                    ("nvim".into(), "Neovim".into()),
                    ("nano".into(), "Nano".into()),
                    ("emacs".into(), "Emacs".into()),
                    ("code".into(), "VS Code".into()),
                    ("subl".into(), "Sublime Text".into()),
                ]),
                default: "vim".into(),
            },
            OptionDef {
                key: "VISUAL".into(),
                label: "Visual Editor".into(),
                help: "Editor for visual editing (used by git, etc.)".into(),
                section: "Environment".into(),
                kind: OptionKind::Dropdown(vec![
                    ("vim".into(), "Vim".into()),
                    ("nvim".into(), "Neovim".into()),
                    ("nano".into(), "Nano".into()),
                    ("emacs".into(), "Emacs".into()),
                    ("code --wait".into(), "VS Code".into()),
                    ("subl -w".into(), "Sublime Text".into()),
                ]),
                default: "vim".into(),
            },
            OptionDef {
                key: "LANG".into(),
                label: "Locale".into(),
                help: "Set the system locale".into(),
                section: "Environment".into(),
                kind: OptionKind::Dropdown(vec![
                    ("en_US.UTF-8".into(), "English (US)".into()),
                    ("en_GB.UTF-8".into(), "English (UK)".into()),
                    ("de_DE.UTF-8".into(), "German".into()),
                    ("fr_FR.UTF-8".into(), "French".into()),
                    ("ja_JP.UTF-8".into(), "Japanese".into()),
                    ("zh_CN.UTF-8".into(), "Chinese (Simplified)".into()),
                ]),
                default: "en_US.UTF-8".into(),
            },
            // History
            OptionDef {
                key: "HISTSIZE".into(),
                label: "History Size".into(),
                help: "Number of commands to keep in memory".into(),
                section: "History".into(),
                kind: OptionKind::Number { min: 100, max: 100000, step: 1000 },
                default: "10000".into(),
            },
            OptionDef {
                key: "HISTFILESIZE".into(),
                label: "History File Size".into(),
                help: "Number of commands to keep in history file".into(),
                section: "History".into(),
                kind: OptionKind::Number { min: 100, max: 200000, step: 1000 },
                default: "20000".into(),
            },
            OptionDef {
                key: "HISTCONTROL".into(),
                label: "History Control".into(),
                help: "How duplicate and space-prefixed commands are handled".into(),
                section: "History".into(),
                kind: OptionKind::Dropdown(vec![
                    ("ignoredups".into(), "Ignore duplicates".into()),
                    ("ignorespace".into(), "Ignore space-prefixed".into()),
                    ("ignoreboth".into(), "Ignore both".into()),
                    ("erasedups".into(), "Erase all duplicates".into()),
                ]),
                default: "ignoreboth".into(),
            },
            OptionDef {
                key: "hist_append".into(),
                label: "Append History".into(),
                help: "Append to history file instead of overwriting".into(),
                section: "History".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            // Shell Options
            OptionDef {
                key: "checkwinsize".into(),
                label: "Check Window Size".into(),
                help: "Update LINES and COLUMNS after each command".into(),
                section: "Shell Options".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "globstar".into(),
                label: "Globstar".into(),
                help: "Enable ** pattern for recursive matching".into(),
                section: "Shell Options".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "cdspell".into(),
                label: "CD Spell Correction".into(),
                help: "Auto-correct minor cd spelling errors".into(),
                section: "Shell Options".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "autocd".into(),
                label: "Auto CD".into(),
                help: "cd into directory by just typing its name".into(),
                section: "Shell Options".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
            // Aliases
            OptionDef {
                key: "alias_ll".into(),
                label: "ll Alias".into(),
                help: "Create 'll' alias for detailed listing".into(),
                section: "Aliases".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "alias_la".into(),
                label: "la Alias".into(),
                help: "Create 'la' alias for listing all files".into(),
                section: "Aliases".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "alias_grep_color".into(),
                label: "Colored grep".into(),
                help: "Add --color=auto to grep aliases".into(),
                section: "Aliases".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "alias_rm_confirm".into(),
                label: "Safe rm".into(),
                help: "Alias rm to 'rm -i' for confirmation".into(),
                section: "Aliases".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
            OptionDef {
                key: "alias_cp_confirm".into(),
                label: "Safe cp".into(),
                help: "Alias cp to 'cp -i' for confirmation".into(),
                section: "Aliases".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
        ],
    }
}
