use super::schema::{ConfigSchema, DotfileType, OptionDef, OptionKind};

pub fn vimrc_schema() -> ConfigSchema {
    ConfigSchema {
        name: "Vimrc".into(),
        dotfile_type: DotfileType::Vimrc,
        default_path: "~/.vimrc".into(),
        options: vec![
            // Appearance
            OptionDef {
                key: "colorscheme".into(),
                label: "Color Scheme".into(),
                help: "Set the color scheme for syntax highlighting".into(),
                section: "Appearance".into(),
                kind: OptionKind::Dropdown(vec![
                    ("default".into(), "Default".into()),
                    ("desert".into(), "Desert".into()),
                    ("elflord".into(), "Elflord".into()),
                    ("evening".into(), "Evening".into()),
                    ("gruvbox".into(), "Gruvbox".into()),
                    ("industry".into(), "Industry".into()),
                    ("koehler".into(), "Koehler".into()),
                    ("morning".into(), "Morning".into()),
                    ("murphy".into(), "Murphy".into()),
                    ("pablo".into(), "Pablo".into()),
                    ("peachpuff".into(), "Peachpuff".into()),
                    ("ron".into(), "Ron".into()),
                    ("shine".into(), "Shine".into()),
                    ("slate".into(), "Slate".into()),
                    ("torte".into(), "Torte".into()),
                    ("zellner".into(), "Zellner".into()),
                ]),
                default: "default".into(),
            },
            OptionDef {
                key: "background".into(),
                label: "Background".into(),
                help: "Set background color hint for color scheme".into(),
                section: "Appearance".into(),
                kind: OptionKind::Dropdown(vec![
                    ("dark".into(), "Dark".into()),
                    ("light".into(), "Light".into()),
                ]),
                default: "dark".into(),
            },
            OptionDef {
                key: "number".into(),
                label: "Line Numbers".into(),
                help: "Show absolute line numbers in the gutter".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "relativenumber".into(),
                label: "Relative Numbers".into(),
                help: "Show relative line numbers (useful for motions like 5j)".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
            OptionDef {
                key: "cursorline".into(),
                label: "Cursor Line".into(),
                help: "Highlight the line the cursor is on".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "cursorcolumn".into(),
                label: "Cursor Column".into(),
                help: "Highlight the column the cursor is on".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
            OptionDef {
                key: "syntax".into(),
                label: "Syntax Highlighting".into(),
                help: "Enable language-aware syntax coloring".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "termguicolors".into(),
                label: "True Color (24-bit)".into(),
                help: "Enable 24-bit RGB colors in the terminal".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
            OptionDef {
                key: "showcmd".into(),
                label: "Show Command".into(),
                help: "Show partial command in the last line of the screen".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "showmode".into(),
                label: "Show Mode".into(),
                help: "Show -- INSERT --, -- VISUAL --, etc. in the status line".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "ruler".into(),
                label: "Ruler".into(),
                help: "Show line and column number of the cursor in the status line".into(),
                section: "Appearance".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "laststatus".into(),
                label: "Status Line".into(),
                help: "When to display the status line".into(),
                section: "Appearance".into(),
                kind: OptionKind::Dropdown(vec![
                    ("0".into(), "Never".into()),
                    ("1".into(), "Only with splits".into()),
                    ("2".into(), "Always".into()),
                ]),
                default: "2".into(),
            },
            OptionDef {
                key: "signcolumn".into(),
                label: "Sign Column".into(),
                help: "When to show the sign column (used by linters/git plugins)".into(),
                section: "Appearance".into(),
                kind: OptionKind::Dropdown(vec![
                    ("auto".into(), "Auto (when signs exist)".into()),
                    ("yes".into(), "Always".into()),
                    ("no".into(), "Never".into()),
                ]),
                default: "auto".into(),
            },

            // Indentation
            OptionDef {
                key: "expandtab".into(),
                label: "Indent With Spaces".into(),
                help: "Insert spaces when pressing Tab instead of a tab character".into(),
                section: "Indentation".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "tabstop".into(),
                label: "Tab Width".into(),
                help: "Number of spaces a tab character displays as".into(),
                section: "Indentation".into(),
                kind: OptionKind::Number { min: 1, max: 16, step: 1 },
                default: "4".into(),
            },
            OptionDef {
                key: "softtabstop".into(),
                label: "Soft Tab Stop".into(),
                help: "Number of spaces inserted when pressing Tab (0 = use tabstop value)".into(),
                section: "Indentation".into(),
                kind: OptionKind::Number { min: 0, max: 16, step: 1 },
                default: "4".into(),
            },
            OptionDef {
                key: "shiftwidth".into(),
                label: "Shift Width".into(),
                help: "Number of spaces for each level of auto-indent (>> and <<)".into(),
                section: "Indentation".into(),
                kind: OptionKind::Number { min: 1, max: 16, step: 1 },
                default: "4".into(),
            },
            OptionDef {
                key: "autoindent".into(),
                label: "Auto Indent".into(),
                help: "Copy indent from current line when starting a new line".into(),
                section: "Indentation".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "smartindent".into(),
                label: "Smart Indent".into(),
                help: "Add extra indent after {, if, etc. in C-like languages".into(),
                section: "Indentation".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "filetype_indent".into(),
                label: "Filetype Indent".into(),
                help: "Load filetype-specific indent rules (filetype indent on)".into(),
                section: "Indentation".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },

            // Search
            OptionDef {
                key: "hlsearch".into(),
                label: "Highlight Search".into(),
                help: "Highlight all matches of the last search pattern".into(),
                section: "Search".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "incsearch".into(),
                label: "Incremental Search".into(),
                help: "Jump to matches while typing the search pattern".into(),
                section: "Search".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "ignorecase".into(),
                label: "Ignore Case".into(),
                help: "Case-insensitive searching".into(),
                section: "Search".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "smartcase".into(),
                label: "Smart Case".into(),
                help: "Override ignorecase when search pattern contains uppercase letters".into(),
                section: "Search".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },

            // Behavior
            OptionDef {
                key: "mouse".into(),
                label: "Mouse Support".into(),
                help: "Enable mouse for clicking, scrolling, and selecting".into(),
                section: "Behavior".into(),
                kind: OptionKind::Dropdown(vec![
                    ("".into(), "Disabled".into()),
                    ("a".into(), "All modes".into()),
                    ("n".into(), "Normal mode only".into()),
                    ("v".into(), "Visual mode only".into()),
                    ("i".into(), "Insert mode only".into()),
                ]),
                default: "a".into(),
            },
            OptionDef {
                key: "clipboard".into(),
                label: "System Clipboard".into(),
                help: "Integrate with the system clipboard for yank/paste".into(),
                section: "Behavior".into(),
                kind: OptionKind::Dropdown(vec![
                    ("".into(), "Disabled (vim registers only)".into()),
                    ("unnamed".into(), "Use * register (selection)".into()),
                    ("unnamedplus".into(), "Use + register (system clipboard)".into()),
                    ("unnamed,unnamedplus".into(), "Both * and + registers".into()),
                ]),
                default: "unnamedplus".into(),
            },
            OptionDef {
                key: "backspace".into(),
                label: "Backspace Behavior".into(),
                help: "What backspace can delete in insert mode".into(),
                section: "Behavior".into(),
                kind: OptionKind::Dropdown(vec![
                    ("indent,eol,start".into(), "Everything (indent, line breaks, past insert start)".into()),
                    ("indent,eol".into(), "Indent and line breaks".into()),
                    ("indent".into(), "Indent only".into()),
                    ("".into(), "Nothing special".into()),
                ]),
                default: "indent,eol,start".into(),
            },
            OptionDef {
                key: "hidden".into(),
                label: "Hidden Buffers".into(),
                help: "Allow switching buffers without saving (keeps changes in memory)".into(),
                section: "Behavior".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "wildmenu".into(),
                label: "Wild Menu".into(),
                help: "Show completion menu when pressing Tab in command-line mode".into(),
                section: "Behavior".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "wrap".into(),
                label: "Line Wrap".into(),
                help: "Visually wrap long lines at the window edge".into(),
                section: "Behavior".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "scrolloff".into(),
                label: "Scroll Offset".into(),
                help: "Minimum lines to keep visible above/below the cursor".into(),
                section: "Behavior".into(),
                kind: OptionKind::Number { min: 0, max: 20, step: 1 },
                default: "5".into(),
            },
            OptionDef {
                key: "splitbelow".into(),
                label: "Split Below".into(),
                help: "Open horizontal splits below the current window".into(),
                section: "Behavior".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "splitright".into(),
                label: "Split Right".into(),
                help: "Open vertical splits to the right of the current window".into(),
                section: "Behavior".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "updatetime".into(),
                label: "Update Time (ms)".into(),
                help: "Milliseconds of inactivity before writing swap file (also used by plugins like gitgutter)".into(),
                section: "Behavior".into(),
                kind: OptionKind::Number { min: 100, max: 4000, step: 100 },
                default: "300".into(),
            },

            // Files & Backup
            OptionDef {
                key: "encoding".into(),
                label: "Encoding".into(),
                help: "Character encoding used inside Vim".into(),
                section: "Files & Backup".into(),
                kind: OptionKind::Dropdown(vec![
                    ("utf-8".into(), "UTF-8".into()),
                    ("latin1".into(), "Latin-1 (ISO 8859-1)".into()),
                    ("cp1252".into(), "Windows-1252".into()),
                ]),
                default: "utf-8".into(),
            },
            OptionDef {
                key: "undofile".into(),
                label: "Persistent Undo".into(),
                help: "Save undo history to file so you can undo after closing and reopening".into(),
                section: "Files & Backup".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
            OptionDef {
                key: "backup".into(),
                label: "Backup Files".into(),
                help: "Keep a backup file before overwriting (filename~)".into(),
                section: "Files & Backup".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
            OptionDef {
                key: "swapfile".into(),
                label: "Swap Files".into(),
                help: "Use swap files for crash recovery".into(),
                section: "Files & Backup".into(),
                kind: OptionKind::Toggle,
                default: "false".into(),
            },
            OptionDef {
                key: "autoread".into(),
                label: "Auto Read".into(),
                help: "Automatically re-read files changed outside of Vim".into(),
                section: "Files & Backup".into(),
                kind: OptionKind::Toggle,
                default: "true".into(),
            },
        ],
    }
}
